version: "3"
services:
  web:
    build:
      context: .
      args:
          BUILD_ENV: development
      dockerfile: Dockerfile
    env_file: .dev.env
    links:
      - db
    ports:
      - 80:80
    volumes:
      - .:/attendance
    container_name: attendance
    depends_on:
      - db
  db:
    image: mysql:5.6
    command: mysqld --sql_mode=""
    ports:
      - 3306:3306
    volumes:
      - attendancedata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: root
      DB_DATABASE: attendance_development
    container_name: attendance_db

volumes:
  attendancedata: