#combining use of docker-compose.override.yml
#EX: build staging, do following steps:
#ln -s docker-compose.staging.yml docker-compose.override.yml
#docker-compose up (or build)
version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/attendance
    container_name: attendance