version: '3'
services:
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - 80:80
      - 443:443
    environment:
      WEB_HOSTNAME: localhost
      CANVAS_API_BASE: https://txstate.test.instructure.com/api
      OAUTH_SECRET: supersecret
    env_file: .env
    volumes:
      - ./app:/usr/app/app
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - attendancedata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: attendance
  fakecas:
    image: registry.its.txstate.edu/cas-stub:base
    ports:
      - 2000:80
volumes:
  attendancedata: {}
